package me.nickimpact.pixelmon.modelconverter.ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.*;
import java.io.File;
import java.util.function.Consumer;

public class FileSelector {

    private JFileChooser selector;
    private JPanel panel;

    public FileSelector(Consumer<File> consumer) {
        this.selector.addChoosableFileFilter(new FileNameExtensionFilter("Jar Files", "jar"));
        if (this.selector.showOpenDialog(this.panel) == 0) {
            consumer.accept(this.selector.getSelectedFile());
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        selector = new JFileChooser();
        selector.setAcceptAllFileFilterUsed(false);
        selector.setAutoscrolls(false);
        selector.setDialogTitle("Select your Input");
        selector.setDialogType(0);
        selector.setEnabled(false);
        selector.setFileSelectionMode(2);
        selector.setName("Select Input");
        panel.add(selector, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
